server {
    listen 80;
    server_name config.nightfall.celo-sepolia.celo-testnet.org nightfall.celo-sepolia.celo-testnet.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name config.nightfall.celo-sepolia.celo-testnet.org;

    ssl_certificate     /etc/letsencrypt/live/config.nightfall.celo-sepolia.celo-testnet.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/config.nightfall.celo-sepolia.celo-testnet.org/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 30G;
    # Increase if you need to upload larger files
    client_body_timeout 3600s;
    send_timeout         3600s;
    keepalive_timeout    75s;

    location / {
        root /var/www/html;
        dav_methods  PUT DELETE MKCOL COPY MOVE;
        create_full_put_path on;
        dav_access group:rw  all:r;
    }
}

server {
    listen 443 ssl;
    server_name nightfall.celo-sepolia.celo-testnet.org;

    ssl_certificate     /etc/letsencrypt/live/nightfall.celo-sepolia.celo-testnet.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nightfall.celo-sepolia.celo-testnet.org/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 50m;

    location / {
        proxy_pass http://nf4_indie_proposer:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
